-- Re-create the Andon Logs table with Foreign Keys
-- We drop it first to ensure schema changes (FKs) are applied if you ran the previous script.
DROP TABLE IF EXISTS public.andon_loglari;

CREATE TABLE public.andon_loglari (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Foreign Keys for Data Integrity
    machine_id UUID NOT NULL REFERENCES public.machines(id),
    operator_id UUID NOT NULL REFERENCES public.operators(id),
    sirket_id UUID REFERENCES public.sirketler(id), -- Nullable if not strict, but good to have
    
    -- Snapshot Data (in case referenced names change later)
    operator_name TEXT, 
    
    -- Core Fields
    type TEXT NOT NULL, -- 'MAINTENANCE' (Bakım) or 'MATERIAL' (Malzeme)
    status TEXT DEFAULT 'PENDING', -- 'PENDING', 'RESPONDING', 'RESOLVED'
    
    -- Responder Info (Filled via Telegram Webhook)
    responder_name TEXT, 
    responded_at TIMESTAMPTZ,
    
    -- Resolution Info
    resolved_at TIMESTAMPTZ
);

-- Enable RLS
ALTER TABLE public.andon_loglari ENABLE ROW LEVEL SECURITY;

-- Policy: Open access for reading/creating (Simplification for MVP)
CREATE POLICY "Enable read access for all" ON public.andon_loglari FOR SELECT USING (true);
CREATE POLICY "Enable insert for all" ON public.andon_loglari FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all" ON public.andon_loglari FOR UPDATE USING (true);

-- Enable Realtime
-- This is crucial for the "Bakımcı Geliyor" instant feedback
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE public.andon_loglari;
COMMIT;
-- Note: In some Supabase setups, you might just need:
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.andon_loglari;
-- But the above acts as a reset/ensure. If you have other tables, use ADD TABLE instead:
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.andon_loglari;

COMMENT ON TABLE public.andon_loglari IS 'Transactional logs for internal help requests (Andon)';
