-- 1. Create Machines Table
create table if not exists machines (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Insert Default Machine (if not exists)
insert into machines (name)
select 'Makine 1'
where not exists (select 1 from machines);

-- 3. Get ID of Machine 1 (Assuming it's 1, but let's be safe if ID generation differs, though usually 1)
-- For simplicity in this script we assume the first machine is ID 1. 
-- In a real scenario we'd capture the ID. Since we just inserted it, let's assume '1' is the text ID we are using in the other tables.
-- Update: The other tables use text or int? Reviewing previous schema... 
-- I added `machine_id text` in the previous step. So we will use the string representation of the ID.

-- 4. Migrate NULL data to Machine 1 (id='1')
-- Operators
UPDATE operators 
SET machine_id = '1' 
WHERE machine_id IS NULL;

-- Stop Reasons
UPDATE stop_reasons 
SET machine_id = '1' 
WHERE machine_id IS NULL;

-- Error Reasons
UPDATE error_reasons 
SET machine_id = '1' 
WHERE machine_id IS NULL;

-- Error Logs (hata_loglari)
UPDATE hata_loglari 
SET machine_id = '1' 
WHERE machine_id IS NULL;

-- Stop Logs (durus_loglari)
UPDATE durus_loglari 
SET machine_id = '1' 
WHERE machine_id IS NULL;

-- Part Logs (sorunsuz_parca_loglari)
UPDATE sorunsuz_parca_loglari 
SET machine_id = '1' 
WHERE machine_id IS NULL;

