-- 1. Sorunsuz Parça Logları
create table sorunsuz_parca_loglari (
  id bigint generated by default as identity primary key,
  operator_id uuid references auth.users not null,
  adet integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Hata Logları
create table hata_loglari (
  id bigint generated by default as identity primary key,
  operator_id uuid references auth.users not null,
  sebep text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Duruş Logları (Session Based)
create table durus_loglari (
  id bigint generated by default as identity primary key,
  operator_id uuid references auth.users not null,
  baslangic timestamp with time zone default timezone('utc'::text, now()) not null,
  bitis timestamp with time zone, -- NULL means currently running
  sebep text -- Filled when stopped
);

-- RLS Policies (Optional but recommended)
-- Enable RLS
alter table sorunsuz_parca_loglari enable row level security;
alter table hata_loglari enable row level security;
alter table durus_loglari enable row level security;

-- Policies for authenticated users to insert
create policy "Enable insert for authenticated users only" on sorunsuz_parca_loglari for insert to authenticated with check (true);
create policy "Enable insert for authenticated users only" on hata_loglari for insert to authenticated with check (true);
create policy "Enable insert for authenticated users only" on durus_loglari for insert to authenticated with check (true);

-- Policies for authenticated users to update (for stop)
create policy "Enable update for authenticated users only" on durus_loglari for update to authenticated using (true);

-- Policies for public read (if needed, similar to operators table)
create policy "Enable read access for all users" on sorunsuz_parca_loglari for select using (true);
create policy "Enable read access for all users" on hata_loglari for select using (true);
create policy "Enable read access for all users" on durus_loglari for select using (true);
