-- FIX: Hata Loglari ID & Error Reasons RLS

-- 1. Restore 'id' column in 'hata_loglari' (User deleted it)
-- We drop it first to ensure we are adding it correctly as a Primary Key Identity.
ALTER TABLE public.hata_loglari DROP COLUMN IF EXISTS id CASCADE;

ALTER TABLE public.hata_loglari
ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- 2. Restore Visibility of Error Reasons (RLS Fix)
-- Since operators are now "RFID users" (Anonymous in Supabase Auth terms),
-- they need public read access to the reason lists.

-- Enable RLS (just in case)
ALTER TABLE public.error_reasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stop_reasons ENABLE ROW LEVEL SECURITY;

-- Allow Public Read for Error Reasons
DROP POLICY IF EXISTS "Public Read Error Reasons" ON public.error_reasons;
CREATE POLICY "Public Read Error Reasons"
ON public.error_reasons FOR SELECT
TO anon, authenticated, public
USING (true);

-- Allow Public Read for Stop Reasons
DROP POLICY IF EXISTS "Public Read Stop Reasons" ON public.stop_reasons;
CREATE POLICY "Public Read Stop Reasons"
ON public.stop_reasons FOR SELECT
TO anon, authenticated, public
USING (true);

-- 3. Verify
COMMENT ON COLUMN public.hata_loglari.id IS 'Restored Primary Key';
